### PR TITLE
Detect long push on CLR

### PR DESCRIPTION
**Pull request by squirreldev-fs**
Hi,

Thanks for this script!
I don't own the Octavi IFR-1 (yet?) but thought I might help detecting long pushes on the CLR button. I thus advise you to test it before accepting this pull request ;-)
I think the code in my commit is self-explanatory, so I don't comment it.

### CODE REVIEW

**Comment by acehoss** [comment]
Close, but this will detect the button release, not a long press. You'd have to use something like the `sim_time` dataref variable to detect the long press by measuring the amount of time since the button press.

Detecting the long press is not the problem, though, the problem is that there is no command to tell X-Plane that the button has been held. [X-Plane Command Search](https://www.siminnovations.com/xplane/command/)

**Comment by acehoss** [comment]
Sorry, I may have dismissed this a little too early--I didn't notice the `command_end` call, and I'll give that a try quick. Maybe that's the secret sauce.

**Comment by acehoss** [comment]
Yep, this is actually a perfect solution. Thanks!

**Comment by squirreldev-fs** [comment]
Glad to read this!

**Pull request merged**
